# Heart Disease — Exploratory Data Analysis

# import libraries

In [1]:
import pandas as pd

# Load dataset

In [2]:
df = pd.read_csv('heart.csv')

In [3]:
# check first 10 rows
df.head(10)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
5,58,0,0,100,248,0,0,122,0,1.0,1,0,2,1
6,58,1,0,114,318,0,2,140,0,4.4,0,3,1,0
7,55,1,0,160,289,0,0,145,1,0.8,1,1,3,0
8,46,1,0,120,249,0,0,144,0,0.8,2,0,3,0
9,54,1,0,122,286,0,0,116,1,3.2,1,2,2,0

In [4]:
# check information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1025 non-null   int64
 4   chol      1025 non-null   int64
 5   fbs       1025 non-null   int64
 6   restecg   1025 non-null   int64
 7   thalach   1025 non-null   int64
 8   exang     1025 non-null   int64
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64
 11  ca        1025 non-null   int64
 12  thal      1025 non-null   int64
 13  target    1025 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 112.2 KB

In [5]:
# check shape
df.shape

(1025, 14)

In [6]:
# check size
df.size

14350

In [7]:
# check data types
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [8]:
# check columns
df.columns.tolist()

['age',
 'sex',
 'cp',
 'trestbps',
 'chol',
 'fbs',
 'restecg',
 'thalach',
 'exang',
 'oldpeak',
 'slope',
 'ca',
 'thal',
 'target']

# Check missing values

In [9]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [10]:
df.isin(['?']).sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

# check duplicate values

In [11]:
df.duplicated().sum()

np.int64(723)

In [12]:
df.shape

(1025, 14)

# Drop Duplicates

In [13]:
df = df.drop_duplicates()
df.shape

(302, 14)

In [14]:
df.duplicated().sum()

np.int64(0)

# Correct Data types

In [15]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [16]:
# Correct gender column
df['sex'] = df['sex'].map({1: 'Male', 0: 'Female'})

In [17]:
# correct exange column
df['exang'] = df['exang'].map({1: 'Yes', 0: 'No'})

In [18]:
# Correct fbs column
df['fbs'] = df['fbs'].map({1: 'High', 0: 'Normal'})

In [19]:
# Check column
df.columns.tolist()

['age',
 'sex',
 'cp',
 'trestbps',
 'chol',
 'fbs',
 'restecg',
 'thalach',
 'exang',
 'oldpeak',
 'slope',
 'ca',
 'thal',
 'target']

# Correct column name

In [20]:
df.columns = df.columns.str.strip()

In [21]:
df.describe()

,age,cp,trestbps,chol,restecg,thalach,oldpeak,slope,ca,thal,target
count,302.00000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000
mean,54.42053,0.963576,131.602649,246.500000,0.526490,149.569536,1.043046,1.397351,0.718543,2.314570,0.543046
std,9.04797,1.032044,17.563394,51.753489,0.526027,22.903527,1.161452,0.616274,1.006748,0.613026,0.498970
min,29.00000,0.000000,94.000000,126.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,48.00000,0.000000,120.000000,211.000000,0.000000,133.250000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.50000,1.000000,130.000000,240.500000,1.000000,152.500000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.00000,2.000000,140.000000,274.750000,1.000000,166.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.00000,3.000000,200.000000,564.000000,2.000000,202.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [22]:
# Kitni rows affected hain check 
print((df['ca'] == 4).sum())
print((df['thal'] == 0).sum())

4
2

In [23]:
# Drop
df = df[df['ca'] != 4]
df = df[df['thal'] != 0]

In [24]:
df.shape

(296, 14)

# Connect to MS SQL Server

In [25]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

# SQL Server connection
host = r"DESKTOP-N9K70SP\SQLEXPRESS"
database = "HeartDiseaseDB"

# ODBC Driver
driver = quote_plus("ODBC Driver 17 for SQL Server")

# Create SQL Server connection
engine = create_engine(
    f"mssql+pyodbc://@{host}/{database}"
    f"?driver={driver}&trusted_connection=yes"
)

# Write DataFrame to SQL Server
df.to_sql(
    "heart",
    engine,
    if_exists="replace",
    index=False
)

# Read back sample
result = pd.read_sql(
    "SELECT TOP 5 * FROM heart;", engine )

result

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,Male,0,125,212,Normal,1,168,No,1.0,2,2,3,0
1,53,Male,0,140,203,High,0,155,Yes,3.1,0,0,3,0
2,70,Male,0,145,174,Normal,1,125,Yes,2.6,0,0,3,0
3,61,Male,0,148,203,Normal,1,161,No,0.0,2,1,3,0
4,62,Female,0,138,294,High,1,106,No,1.9,1,3,2,0